### ISSUE TITLE
Incomplete arima spec in output

### ISSUE THREAD

**Issue by merangelik** [rjdverse/rjd3x13#27]
Hi,

should `output$preprocessing$description$arima`also contain the remaining `p, q, bp` and `bq` values of the arima spec instead of only `d`and `bd`? Or do these values mean something completely different?

```{r}
> userdefined_default <- c(
+   "y", "t", "sa", "s", "i", "cal", "y_f", "t_f", "sa_f", "s_f", 
+   "cal_f", "y_ef",
+   "decomposition.d6", "decomposition.d7", "decomposition.d9","decomposition.d13",
+   "decomposition.mode", "arima.p","arima.d", "arima.q" ,"arima.bp" , "arima.bd","arima.bq"
+ )
> output <- fast_x13(
+   ts = AirPassengers,
+   spec = "rsa1",# dieser Parameter anscheinend nicht case sensitive
+   context = NULL,
+   userdefined = userdefined_default
+ )
> 
> names(output$preprocessing$description$arima)
[1] "period" "d"      "bd"     "phi"    "theta"  "bphi"   "btheta"
```

**Comment by AQLT** [comment]
The values of p, q, bp, bq can be obtained with phi, theta, bphi and btheta. See for example what is done in rjd3report or in rjd3toolkit print methods'
https://github.com/AQLT/rjd3report/blob/master/R/manipulation.R#L48-L64

**Comment by annasmyk** [comment]
I think we can close this one
