### ISSUE TITLE
Difference between `decomposition` and `finals`

### ISSUE THREAD

**Issue by TanguyBarthelemy** [rjdverse/rjd3x13#58]
In the output of `x13` function some series are duplicated between `decomposition` and `finals`.

For example:

``` r
x <- AirPassengers +
    c(rep(0, 100), 200, rep(0, 43)) + # Ajout d'un AO en mai 1957
    c(rep(0, 80), rep(-100, 64)) # Ajout d'un LS en septembre 1955
plot(x)
```
![image](https://github.com/user-attachments/assets/a5eab27a-7498-4434-9727-b1384762c04f)

<sup>Created on 2024-10-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### `d11`

There are 2 variables `decomposition.d11` and `finals.d11`.

``` r
mod_v3 <- rjd3x13::x13(x, spec = "RSA3", userdefined = c("decomposition.d11", "finals.d11"))
d11 <- cbind(mod_v3$user_defined$finals.d11, mod_v3$user_defined$decomposition.d11)
ts.plot(d11, col = c("blue", "red"), lwd = c(2, 1))
legend("left", c("finals.d11", "decomposition.d11"), col = c("blue", "red"), lwd = c(2, 1))
```
![image](https://github.com/user-attachments/assets/5bb981d2-4e55-4628-9d58-2e81ac37db00)

<sup>Created on 2024-10-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### `d12`

Same thing for `d12`

``` r
mod_v3 <- rjd3x13::x13(x, spec = "RSA3", userdefined = c("decomposition.d12", "finals.d12"))
d12 <- cbind(mod_v3$user_defined$finals.d12, mod_v3$user_defined$decomposition.d12)
ts.plot(d12, col = c("blue", "red"), lwd = c(2, 1))
legend("left", c("finals.d12", "decomposition.d12"), col = c("blue", "red"), lwd = c(2, 1))
```
![image](https://github.com/user-attachments/assets/b8fe4cd1-93bd-4820-80b9-3f1ad632e384)

<sup>Created on 2024-10-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### `d13`

Same thing for `d13`

``` r
mod_v3 <- rjd3x13::x13(x, spec = "RSA3", userdefined = c("decomposition.d13", "finals.d13"))
d13 <- cbind(mod_v3$user_defined$finals.d13, mod_v3$user_defined$decomposition.d13)
ts.plot(d13, col = c("blue", "red"), lwd = c(2, 1))
legend("left", c("finals.d13", "decomposition.d13"), col = c("blue", "red"), lwd = c(2, 1))
```
![image](https://github.com/user-attachments/assets/632f2d0c-00a3-4ff3-b491-499cf678d8fd)

<sup>Created on 2024-10-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

It seems that the `d` series in `decomposition` are corrected from the outliers (linearised series).
Should this series be renamed?

**Comment by AQLT** [comment]
Yes this is not as in V2 where the final components of the decomposition table also includes the pre-processing. In V3 you clearly separate the pre-processing, the decomposition and the final components (finals). This allow to more easily compute some statistics (for example the residual seasonality tests are made on the decomposition table and not the final tables). For example, those components where recently added in `RJDemetra` (https://github.com/rjdverse/rjdemetra/pull/139)

**Comment by TanguyBarthelemy** [comment]
Ok yes, but I add in mind that the `d11` component referred to a single series. So why are `finals.d11` and `decomposition.d11` different? Shouldn't we be talking about linearised series instead or in the X11 process, isn't there another name for these series with or without outliers?

**Comment by annasmyk** [comment]
we discussed this, I close it for now
